project:
  type: book
  output-dir: docs

book:
  title: "Transformação e Manipulação de Dados com a linguagem R"
  author: "Eric Scopinho"
#  date: "8/24/2022"
  cover-image: images/cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - Importacao/Importacao_de_dados_com_tidyverse.qmd
    - Organizacao/Organizacao_de_dados_com_tidyr.qmd
    - Transformacao/Transformacao_de_dados_com_dplyr.qmd
    - Manipulacao_Strings/Manipulacao de strings com stringr.qmd
    - DataHora/Datas_e_horas_com_lubridate.qmd
    - Visualizacao/Visualizacao_de_dados_com_ggplot2.qmd

bibliography: references.bib


format: 
  html: 
    df-print: paged
    link-external-icon: true
    link-external-newwindow: true
    toc: true
#    toc-location: left
    toc-depth: 4
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
execute: 
  warning: false
lang: pt
license: "CC BY"

