# Bem-Vindo {.unnumbered}

Este livro eletrônico contém uma série de informações sobre transformação e manipulação de dados utilizando a **linguagem R**, mais especificamente o pacote **tidyverse**.

Estas são etapas muito importantes para quem trabalha com dados, como por exemplo uma área de negócio de uma organização, buscando tomar decisões com base em seus dados, ou até mesmo no ciclo de vida de um projeto de ciência de dados.

A comunidade R tem produzido ao longo dos anos uma série [Folhas de Referências](https://www.rstudio.com/resources/cheatsheets/) (*cheatsheets*) que fazem parte também da ferramenta de desenvolvimento [RStudio](http://localhost:7802/rstudio.com).

Estas **Folhas de Referências**, são anotações de uma ou duas páginas que visam resumir as principais informações sobre determinado tema ou pacote do R. São uma espécie de "cola" para nos lembrarmos dos comandos e informações mais relevantes.

Este livro se baseia nestas folhas de referências, que apesar de extremamente úteis, podem ser de difícil interpretação para usuários iniciantes.

Outro motivador para este livro, foi a escassez de documentação sobre o tema em língua Portuguesa, que apesar dos grandes esforços da comunidade brasileira e voluntários, ainda sofre com falta de acesso para quem não domina o idioma inglês.

::: callout-warning
Para melhor utilizar o conteúdo deste livro, é importante que você já possua uma introdução à linguagem R e saiba carregar pacotes (packages) no R. Não iremos abortar comandos básicos da linguagem e nem mesmo instalação da ferramenta de desenvolvimento.

Para mais informações acesse:

<https://education.rstudio.com/learn/beginner/>.
:::

**Os temas abordados neste livro são:**

-   [Importação de Dados](./Importacao/Importacao_de_dados_com_tidyverse.html): Trata sobre **importação de dados** tabulados (.csv, .tsv, .txt), planilhas do Excel e Google Sheets, através do pacote **tidyverse (readr, readxl and googlesheets4).** Ver folha de referência: [data-import cheatsheet](https://github.com/scopinho/R-cheatsheets/blob/main/translations/portuguese/data-import_pt_br.pdf).

-   [Organização de Dados](./Organizacao/Organizacao_de_dados_com_tidyr.html): Sobre **organização de dados** com o pacote **tidyr**. Mover colunas e linhas de forma a estruturar seus dados em tabelas organizadas. Ver folha de referência: [tidyr cheatsheet](https://github.com/scopinho/R-cheatsheets/blob/main/translations/portuguese/tidyr_pt_br.pdf).

-   [Transformação de dados](./Transformacao/Transformacao_de_dados_com_dplyr.html) : Apresenta a **transformação de dados** com o pacote **dplyr**. Aplicação de filtros, sumarização, criação de colunas calculadas e muitas outras funções de transformação. Ver folha de referência: [data transformation cheatsheet](https://github.com/scopinho/R-cheatsheets/blob/main/translations/portuguese/data-transformation_pt_br.pdf)

-   [Manipulação de strings](./Manipulacao/Manipulacao%20de%20strings%20com%20stringr.html): Fala sobre **manipulação de strings** (textos) com o pacote **stringr**. Apresenta também um bom conteúdo sobre **expressões** **regulares** (**regex**). Ver folha de referência: [stringr cheatsheet](https://github.com/scopinho/R-cheatsheets/blob/main/translations/portuguese/strings_pt_br.pdf)

-   [Fatores](./Fatores/Fatores_com_forcats.html): Fala sobre **manipulação de strings** (textos) com o pacote **stringr**. Apresenta também um bom conteúdo sobre **expressões** **regulares** (**regex**). Ver folha de referência: [factors cheatsheet](https://github.com/scopinho/R-cheatsheets/blob/main/translations/portuguese/factors_pt_br.pdf)

-   [Datas e horas](./DataHora/Datas_e_horas_com_lubridate.html): Sobre a formatação e cálculos de **variáveis** com **datas** e **horas** com o pacote **lubridate**. Ver folha da referência: [lubridate cheatsheet](https://github.com/scopinho/R-cheatsheets/blob/main/translations/portuguese/lubridate_pt_br.pdf).

-   [Programação Funcional](Funcional/Prog_Funcional_com_purrr.html): Sobre **programação funcional**, **listas** e **funções** com o pacote **purrr**. Ver folha da referência: [purrr cheatsheet](https://github.com/scopinho/R-cheatsheets/blob/main/translations/portuguese/purrr_pt_br.pdf).

-   [Visualização de Dados](./Visualizacao/Visualizacao_de_dados_com_ggplot2.html): Traz uma introdução à criação de gráficos através do pacote **ggplot2** e também uma introdução ao pacote **gt** para criação de tabelas de relatórios. Ver folha da referência: [data visualization cheatsheet](https://github.com/scopinho/R-cheatsheets/blob/main/translations/portuguese/data-visualization_pt.pdf).

::: {.callout-note appearance="simple"}
Este livro é gerado à partir do sitema de publicação [Quarto](https://www.quarto.org).
:::

## Licença

::: {.callout-note appearance="simple"}
Este livro é uma pequena contribuição à comunidade de software livre. Ele é (e sempre será) **livre**, e está licenciado sob a [Creative Commons Attribution-NonCommercial-NoDerivs 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) License.

Se você quiser contribuir, por favor, considere em reportar algum erro ou sugestão em [github.com/scopinho/Livro_Transform_Dados_R](https://github.com/scopinho/Livro_Transform_Dados_R).
:::
